#!/usr/bin/env bash
# context-os: Make Claude Code use fewer tokens. Zero dependencies.
# Usage: curl -fsSL https://raw.githubusercontent.com/sravan27/context-os/main/setup.sh | bash
set -euo pipefail

# --- Generate CLAUDE.md ---
MARKER_START="<!-- context-os:start -->"
MARKER_END="<!-- context-os:end -->"

BLOCK="$MARKER_START
# Response rules

- Ultra-concise. No preamble, no recap, no filler.
- Code > explanation. Show the diff, not why you chose it.
- 1-2 sentence plan, then execute. Never explain what you're about to do.
- If asked to explain, use fragments. Drop articles. Be direct.

# Repo rules

- Use the map below. Don't explore or scan.
- Read only files you'll change.
- Batch edits. One response, multiple files.
- On errors, show only the error. Skip passing output.

# Session continuity

If a restart packet or \`.context-os/handoff.md\` exists, read it first. Resume from there. Don't re-attempt failed approaches.
$MARKER_END"

if [ -f CLAUDE.md ]; then
  if grep -q "$MARKER_START" CLAUDE.md; then
    # Replace existing block (macOS + Linux compatible sed)
    python3 -c "
import re, sys
text = open('CLAUDE.md').read()
block = '''$BLOCK'''
text = re.sub(r'$MARKER_START.*?$MARKER_END', block, text, flags=re.DOTALL)
open('CLAUDE.md', 'w').write(text)
" 2>/dev/null || echo "  (could not update existing block, skipping)"
    echo "  updated context-os block in CLAUDE.md"
  else
    printf '\n\n%s\n' "$BLOCK" >> CLAUDE.md
    echo "  appended context-os block to CLAUDE.md"
  fi
else
  printf '%s\n' "$BLOCK" > CLAUDE.md
  echo "  created CLAUDE.md"
fi

# --- Generate .claudeignore ---
if [ ! -f .claudeignore ]; then
  IGNORES=""
  for dir in node_modules .next dist build target __pycache__ .venv venv .tox coverage .nyc_output .gradle .idea .vs vendor Pods .dart_tool; do
    [ -d "$dir" ] && IGNORES="$IGNORES$dir/
"
  done
  IGNORES="${IGNORES}*.lock
*.min.js
*.min.css
*.map
.context-os/
"
  printf '# Generated by context-os\n%s' "$IGNORES" > .claudeignore
  echo "  created .claudeignore"
fi

# --- Add .context-os/ to .gitignore ---
if [ -f .gitignore ]; then
  grep -q '.context-os' .gitignore || printf '\n.context-os/\n' >> .gitignore
else
  printf '.context-os/\n' > .gitignore
fi

echo ""
echo "  done. Start a new Claude Code session to use the optimized CLAUDE.md."
echo ""
echo "  For automatic test/build output reduction, install the full binary:"
echo "    cargo install --git https://github.com/sravan27/context-os --path apps/cli"
echo "    context-os init"
